name: Demo
on: push
jobs:
  pull:
    runs-on: start-deutsch
    steps:
      - name: set folder and pull
        run: |
          cd /home/start-deutsch/start-deutsch/start_deutsch/
          git pull
  migrations:
    needs: pull
    runs-on: start-deutsch
    steps:
      - name: makemigrations
        run: |
          cd /home/start-deutsch/start-deutsch/start_deutsch/ 
          python manage.py makemigrations
      - name: migrate
        run: python manage.py migrate

