name: Demo
on: workflow_dispatch
jobs:
  pull:
    runs-on: push
    steps:
      - name: set folder
        run: cd /home/start-deutsch/start-deutsch/start_deutsch/
      - name: pull
        run: pwd
  migrations:
    needs: pull
    runs-on: start-deutsch
    steps:
      - name: makemigrations
        run: python manage.py makemigrations
      - name: migrate
        run: python manage.py migrate

