name: Demo
on: push
jobs:
  pull:
    runs-on: start-deutsch
    steps:
      - name: set folder and pull
        run: |
          cd /home/start-deutsch/start-deutsch/start_deutsch/
          git pull
  migrations:
    needs: pull
    runs-on: start-deutsch
    steps:
      - name: migrations
        run: |
          cd /home/start-deutsch/start-deutsch/
          source venv/bin/activate
          cd start_deutsch        
          python manage.py makemigrations
          python manage.py migrate

